# Generated by Django 4.1.3 on 2022-11-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Range date')),
                ('range', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('A', 'Afternoon')], default='M', max_length=1)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.golfer')),
            ],
        ),
    ]
