# Generated by Django 4.1.3 on 2022-11-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_practice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='golfer',
            name='experience',
            field=models.IntegerField(verbose_name='Experience (Years)'),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location (City, State)'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='range',
            field=models.CharField(choices=[('5a', '5:00 AM'), ('6a', '6:00 AM'), ('7a', '7:00 AM'), ('8a', '8:00 AM'), ('9a', '9:00 AM'), ('10a', '10:00 AM'), ('11a', '11:00 AM'), ('12', '12:00 PM'), ('1p', '1:00 PM'), ('2p', '2:00 PM'), ('3p', '3:00 PM'), ('4p', '4:00 PM'), ('5p', '5:00 PM'), ('6p', '6:00 PM'), ('7p', '7:00 PM'), ('8p', '8:00 PM'), ('9p', '9:00 PM'), ('10p', '10:00 PM')], default='5a', max_length=3, verbose_name='Range Time'),
        ),
    ]
