# Generated by Django 4.1.3 on 2022-11-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
