# Generated by Django 4.1.3 on 2022-11-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_course_color_alter_course_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default='Green', max_length=20),
        ),
    ]
