# Generated by Django 4.1.3 on 2022-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_course_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='courses',
            field=models.ManyToManyField(to='main_app.course'),
        ),
    ]
